# Import pandas

## Why pandas?

* Pandas lets us use the full functionality of DATA FRAMES in python
* Why dataframes?
    * Managing large datasets can be easier
    * Organized -- ORDERED AND LABELED
    * Play well with spreadsheets (csv files)

In [1]:
import pandas as pd

# Import a csv file

we use the `pd.read_csv(<path to file>)` function

In [2]:
music = pd.read_csv('../../../data/familiar_music_database_missing.csv')

# Inspecting the Data

Things we might want to do to check our data:
* Look at the first few rows of the dataset (`head()`)
* What *type* of data is stored in each column
* Check for missing data
* Picking columns (or rows)
* Checking the names of the columns
* Know the SHAPE of the dataframe (# of rows, # of columns)
* Know how many entries are duplicated

In [3]:
music

,year,title,artist,id,uri,rank,genre,cover,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,mode,time_signature,duration_ms,start_time
0,1946,Symphony,Freddy Martin,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,1,Jazz,False,0.308,0.172,...,0.0356,0.9020,0.012600,0.1650,0.243,119.056,1.0,4,195213.0,1:49
1,1946,Symphony,Freddy Martin,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,1,Jazz,False,0.308,0.172,...,0.0356,0.9020,0.012600,0.1650,0.243,119.056,1.0,4,195213.0,1:49
2,1946,I Can't Begin To Tell You - Single Version,Bing Crosby,22b0w2VmAj51WGEL5H8PQp,spotify:track:22b0w2VmAj51WGEL5H8PQp,2,Pop,False,0.566,0.125,...,0.0404,0.9660,0.189000,0.1140,0.323,97.665,1.0,4,174600.0,0:08
3,1946,Let It Snow! Let It Snow! Let It Snow!,Vaughn Monroe,75Sx3XuVfvyOL9k02ylrA0,spotify:track:75Sx3XuVfvyOL9k02ylrA0,3,Pop,False,0.516,0.399,...,0.0300,0.9880,0.097000,0.3990,0.478,118.196,1.0,4,188280.0,0:29
4,1946,"Doctor, Lawyer, Indian Chief",Betty Hutton,3beq9XZer07zWfMAQFbcWr,spotify:track:3beq9XZer07zWfMAQFbcWr,4,Pop,False,0.700,0.239,...,0.3210,0.8190,0.000000,0.1380,0.939,176.562,1.0,4,184827.0,0:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3187,1983,Tonight I Celebrate My Love,Roberta Flack,6KgBoqgnh8i6AjU0slFeYe,spotify:track:6KgBoqgnh8i6AjU0slFeYe,96,R&B/Soul,False,0.478,0.286,...,0.0305,0.7700,0.000034,0.1880,0.126,117.445,1.0,4,210360.0,1:22
3188,1983,You Got Lucky,Tom Petty and the Heartbreakers,5Mc4cz1QdX5n2vFV0K10vM,spotify:track:5Mc4cz1QdX5n2vFV0K10vM,97,Rock,False,0.696,0.679,...,0.0268,0.0749,0.000015,0.0712,0.616,114.748,0.0,4,218333.0,0:44
3189,1983,Don't Cry,Asia,5NHEpCtDPugmIuawJtwH2y,spotify:track:5NHEpCtDPugmIuawJtwH2y,98,Rock,False,0.304,0.934,...,0.0709,0.0917,0.000000,0.1580,0.527,147.721,1.0,4,212093.0,1:05
3190,1983,Breaking Us In Two,Joe Jackson,767BYYVKKNdFCI2GrCk4BR,spotify:track:767BYYVKKNdFCI2GrCk4BR,99,Pop,False,0.629,0.563,...,0.0246,0.3340,0.000000,0.1460,0.504,108.868,1.0,4,293133.0,1:10
3191,1983,Fall in Love with Me,"Earth, Wind & Fire",5qugKP8gPqN91O7KBMkW6P,spotify:track:5qugKP8gPqN91O7KBMkW6P,100,R&B/Soul,False,0.862,0.588,...,0.0536,0.1090,0.000452,0.0869,0.778,117.464,1.0,4,352067.0,1:20

# Looking at the first rows

In [4]:
music.head(3)

,year,title,artist,id,uri,rank,genre,cover,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,mode,time_signature,duration_ms,start_time
0,1946,Symphony,Freddy Martin,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,1,Jazz,False,0.308,0.172,...,0.0356,0.902,0.0126,0.165,0.243,119.056,1.0,4,195213.0,1:49
1,1946,Symphony,Freddy Martin,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,1,Jazz,False,0.308,0.172,...,0.0356,0.902,0.0126,0.165,0.243,119.056,1.0,4,195213.0,1:49
2,1946,I Can't Begin To Tell You - Single Version,Bing Crosby,22b0w2VmAj51WGEL5H8PQp,spotify:track:22b0w2VmAj51WGEL5H8PQp,2,Pop,False,0.566,0.125,...,0.0404,0.966,0.1890,0.114,0.323,97.665,1.0,4,174600.0,0:08

In [5]:
music.tail(2)

,year,title,artist,id,uri,rank,genre,cover,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,mode,time_signature,duration_ms,start_time
3190,1983,Breaking Us In Two,Joe Jackson,767BYYVKKNdFCI2GrCk4BR,spotify:track:767BYYVKKNdFCI2GrCk4BR,99,Pop,False,0.629,0.563,...,0.0246,0.334,0.000000,0.1460,0.504,108.868,1.0,4,293133.0,1:10
3191,1983,Fall in Love with Me,"Earth, Wind & Fire",5qugKP8gPqN91O7KBMkW6P,spotify:track:5qugKP8gPqN91O7KBMkW6P,100,R&B/Soul,False,0.862,0.588,...,0.0536,0.109,0.000452,0.0869,0.778,117.464,1.0,4,352067.0,1:20

## Knowing the shape of your dataframe 

`rows, columns`

In [6]:
music.shape

(3192, 22)

# Summary stats of numeric columns (integers/floats)

In [7]:
music.describe()

,year,rank,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,mode,time_signature,duration_ms
count,3192.000000,3192.000000,3192.000000,3191.000000,3190.000000,3192.000000,3192.000000,3192.000000,3191.000000,3192.000000,3192.000000,3191.000000,3190.000000,3192.000000,3.191000e+03
mean,1966.781955,47.209586,0.564079,0.505225,5.194357,-10.633345,0.051632,0.496480,0.052836,0.187071,0.648162,118.347661,0.803135,3.890977,1.969947e+05
std,10.060491,28.875731,0.156780,0.218515,3.571406,3.564819,0.050244,0.306564,0.180502,0.151352,0.242646,28.955860,0.397692,0.372201,6.615341e+04
min,1946.000000,1.000000,0.133000,0.014200,0.000000,-31.483000,0.022400,0.000028,0.000000,0.009670,0.051800,40.120000,0.000000,1.000000,8.946700e+04
25%,1959.000000,22.000000,0.457000,0.338000,2.000000,-12.821750,0.031200,0.213000,0.000000,0.090450,0.465000,97.110500,1.000000,4.000000,1.558130e+05
50%,1967.000000,44.000000,0.576000,0.506000,5.000000,-10.256000,0.036800,0.512000,0.000015,0.131000,0.692000,117.232000,1.000000,4.000000,1.799600e+05
75%,1975.000000,72.000000,0.678250,0.676500,9.000000,-8.147750,0.050900,0.776000,0.001110,0.240250,0.862000,133.691000,1.000000,4.000000,2.215930e+05
max,1983.000000,110.000000,0.965000,0.996000,11.000000,-0.798000,0.881000,0.994000,0.970000,0.976000,0.991000,233.429000,1.000000,5.000000,1.008533e+06

In [8]:
print(type(2))
print(type(2.0))

<class 'int'>
<class 'float'>

In [9]:
music.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              3192 non-null   int64
 1   title             3192 non-null   object
 2   artist            3190 non-null   object
 3   id                3191 non-null   object
 4   uri               3192 non-null   object
 5   rank              3192 non-null   int64
 6   genre             3192 non-null   object
 7   cover             3192 non-null   bool
 8   danceability      3192 non-null   float64
 9   energy            3191 non-null   float64
 10  key               3190 non-null   float64
 11  loudness          3192 non-null   float64
 12  speechiness       3192 non-null   float64
 13  acousticness      3192 non-null   float64
 14  instrumentalness  3191 non-null   float64
 15  liveness          3192 non-null   float64
 16  valence           3192 non-null   float64
 17  tempo             3191 non-null   float64
 18  mode              3190 non-null   float64
 19  time_signature    3192 non-null   int64
 20  duration_ms       3191 non-null   float64
 21  start_time        3192 non-null   object
dtypes: bool(1), float64(12), int64(3), object(6)
memory usage: 526.9+ KB

# More on missing data

In [10]:
music.key.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
3187    False
3188    False
3189    False
3190    False
3191    False
Name: key, Length: 3192, dtype: bool

# Getting column names

In [11]:
# we can put them in a list
col_list = list(music.columns)

In [12]:
col_list

['year',
 'title',
 'artist',
 'id',
 'uri',
 'rank',
 'genre',
 'cover',
 'danceability',
 'energy',
 'key',
 'loudness',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'mode',
 'time_signature',
 'duration_ms',
 'start_time']

In [13]:
music.duplicated()

0       False
1        True
2       False
3       False
4       False
        ...
3187    False
3188    False
3189    False
3190    False
3191    False
Length: 3192, dtype: bool

In [14]:
# take the sume -- there's one duplicate
music.duplicated().sum()

1

# Picking certain columns

2 main ways to reference dataframe columns in pandas
1. `music['danceability']`
2. `music.danceability`

This is like in R when we would do something like `music$danceability`

In [20]:
# gives you back one column JUST as a column (pandas series)
print(type(music['danceability']))
music['danceability']

<class 'pandas.core.series.Series'>

0       0.308
1       0.308
2       0.566
3       0.516
4       0.700
        ...
3187    0.478
3188    0.696
3189    0.304
3190    0.629
3191    0.862
Name: danceability, Length: 3192, dtype: float64

In [21]:
# gives you back a DATAFRAME that has one columns
print(type(music[['danceability']]))
music[['danceability']]

<class 'pandas.core.frame.DataFrame'>

      danceability
0            0.308
1            0.308
2            0.566
3            0.516
4            0.700
...            ...
3187         0.478
3188         0.696
3189         0.304
3190         0.629
3191         0.862

[3192 rows x 1 columns]

In [16]:
music.danceability

0       0.308
1       0.308
2       0.566
3       0.516
4       0.700
        ...
3187    0.478
3188    0.696
3189    0.304
3190    0.629
3191    0.862
Name: danceability, Length: 3192, dtype: float64

In [24]:
# if we ask for a LIST of columns, we get back a dataframe with those columns
music[['danceability', 'key']]

      danceability  key
0            0.308  7.0
1            0.308  7.0
2            0.566  7.0
3            0.516  2.0
4            0.700  8.0
...            ...  ...
3187         0.478  3.0
3188         0.696  9.0
3189         0.304  0.0
3190         0.629  9.0
3191         0.862  0.0

[3192 rows x 2 columns]

In [29]:
column_list_1 = ['key', 'rank', 'artist']
column_list_1

['key', 'rank', 'artist']

In [30]:
music[column_list_1]

      key  rank                           artist
0     7.0     1                    Freddy Martin
1     7.0     1                    Freddy Martin
2     7.0     2                      Bing Crosby
3     2.0     3                    Vaughn Monroe
4     8.0     4                     Betty Hutton
...   ...   ...                              ...
3187  3.0    96                    Roberta Flack
3188  9.0    97  Tom Petty and the Heartbreakers
3189  0.0    98                             Asia
3190  9.0    99                      Joe Jackson
3191  0.0   100               Earth, Wind & Fire

[3192 rows x 3 columns]

In [31]:
# specificy columns to get rid of
music.drop(columns = column_list_1)

,year,title,id,uri,genre,cover,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,mode,time_signature,duration_ms,start_time
0,1946,Symphony,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,Jazz,False,0.308,0.172,-12.093,0.0356,0.9020,0.012600,0.1650,0.243,119.056,1.0,4,195213.0,1:49
1,1946,Symphony,5WwsOFIPbfmLmu7xcxEnUo,spotify:track:5WwsOFIPbfmLmu7xcxEnUo,Jazz,False,0.308,0.172,-12.093,0.0356,0.9020,0.012600,0.1650,0.243,119.056,1.0,4,195213.0,1:49
2,1946,I Can't Begin To Tell You - Single Version,22b0w2VmAj51WGEL5H8PQp,spotify:track:22b0w2VmAj51WGEL5H8PQp,Pop,False,0.566,0.125,-21.128,0.0404,0.9660,0.189000,0.1140,0.323,97.665,1.0,4,174600.0,0:08
3,1946,Let It Snow! Let It Snow! Let It Snow!,75Sx3XuVfvyOL9k02ylrA0,spotify:track:75Sx3XuVfvyOL9k02ylrA0,Pop,False,0.516,0.399,-6.123,0.0300,0.9880,0.097000,0.3990,0.478,118.196,1.0,4,188280.0,0:29
4,1946,"Doctor, Lawyer, Indian Chief",3beq9XZer07zWfMAQFbcWr,spotify:track:3beq9XZer07zWfMAQFbcWr,Pop,False,0.700,0.239,-12.198,0.3210,0.8190,0.000000,0.1380,0.939,176.562,1.0,4,184827.0,0:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3187,1983,Tonight I Celebrate My Love,6KgBoqgnh8i6AjU0slFeYe,spotify:track:6KgBoqgnh8i6AjU0slFeYe,R&B/Soul,False,0.478,0.286,-11.937,0.0305,0.7700,0.000034,0.1880,0.126,117.445,1.0,4,210360.0,1:22
3188,1983,You Got Lucky,5Mc4cz1QdX5n2vFV0K10vM,spotify:track:5Mc4cz1QdX5n2vFV0K10vM,Rock,False,0.696,0.679,-5.731,0.0268,0.0749,0.000015,0.0712,0.616,114.748,0.0,4,218333.0,0:44
3189,1983,Don't Cry,5NHEpCtDPugmIuawJtwH2y,spotify:track:5NHEpCtDPugmIuawJtwH2y,Rock,False,0.304,0.934,-5.169,0.0709,0.0917,0.000000,0.1580,0.527,147.721,1.0,4,212093.0,1:05
3190,1983,Breaking Us In Two,767BYYVKKNdFCI2GrCk4BR,spotify:track:767BYYVKKNdFCI2GrCk4BR,Pop,False,0.629,0.563,-8.020,0.0246,0.3340,0.000000,0.1460,0.504,108.868,1.0,4,293133.0,1:10
3191,1983,Fall in Love with Me,5qugKP8gPqN91O7KBMkW6P,spotify:track:5qugKP8gPqN91O7KBMkW6P,R&B/Soul,False,0.862,0.588,-11.363,0.0536,0.1090,0.000452,0.0869,0.778,117.464,1.0,4,352067.0,1:20